# Generated by Django 5.0.4 on 2024-06-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappChat', '0007_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='sender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='receiver',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='WhatsAppAccount',
        ),
    ]
