# Generated by Django 5.0.4 on 2024-06-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappChat', '0008_alter_conversation_sender_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='phone_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
