# Generated by Django 5.0.4 on 2024-06-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_team_alter_user_team'),
        ('createTeam', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='createTeam.team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
