# Generated by Django 5.0.4 on 2024-06-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0012_alter_user_team_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/avatar.svg', null=True, upload_to='profile_photos/'),
        ),
    ]
