# Generated by Django 5.0.4 on 2024-06-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0013_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
