# Generated by Django 5.0.4 on 2024-06-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0011_team_alter_user_team'),
        ('createTeam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
