# Generated by Django 5.0.4 on 2024-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createTeam', '0005_alter_team_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='apiToken',
            field=models.CharField(default='abcd', max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.UUIDField(default='Sankhla'),
        ),
    ]
