# Generated by Django 5.0.4 on 2024-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createTeam', '0010_remove_team_apitoken_remove_team_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_leader',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
