# Generated by Django 5.0.4 on 2024-07-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createTeam', '0011_team_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='accessToken',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
