# Generated by Django 5.0.4 on 2024-07-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createTeam', '0012_team_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='accessToken',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
