# Generated by Django 5.0.4 on 2024-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createTeam', '0013_alter_team_accesstoken_alter_team_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.CharField(max_length=500),
        ),
    ]
